// wealth-legacy-angular/src/app/components/panels/activity-panel.component.ts
import { Component, computed, inject, signal } from '@angular/core';
import { ACTIVITY_TYPE_COLORS } from '../../data/constants';
import { WealthDriverService } from '../../services/wealth-driver.service';
import { formatRelativeTime } from '../../utils/format';
import { ClientPickerComponent } from '../client-picker/client-picker.component';
import { PanelComponent } from '../panel/panel.component';

@Component({
  selector: 'app-activity-panel',
  standalone: true,
  imports: [PanelComponent, ClientPickerComponent],
  template: `
    <app-panel title="ACTIVITY" [scroll]="true" [right]="true">
      <app-client-picker panelRight [value]="clientId()" (valueChange)="clientId.set($event)" />
      <ul class="divide-y divide-halo-border/30">
        @for (item of items(); track item.id) {
          <li class="px-2.5 py-1.5">
            <div class="flex items-baseline gap-2">
              <span
                class="text-2xs font-bold tracking-wider"
                [style.color]="typeColors[item.type]"
              >
                {{ item.type }}
              </span>
              <span class="text-2xs text-halo-dim num ml-auto">{{
                formatRelativeTime(item.time)
              }}</span>
            </div>
            <div class="text-xs text-halo-text mt-0.5 leading-snug">{{ item.headline }}</div>
            @if (item.detail) {
              <div class="text-2xs text-halo-muted leading-snug mt-0.5">{{ item.detail }}</div>
            }
          </li>
        }
      </ul>
    </app-panel>
  `,
})
export class ActivityPanelComponent {
  private readonly driver = inject(WealthDriverService);

  protected readonly state = this.driver.stateSignal;
  protected readonly clientId = signal('C001');
  protected readonly typeColors = ACTIVITY_TYPE_COLORS;
  protected readonly formatRelativeTime = formatRelativeTime;

  items = computed(() =>
    this.state()
      .activity.filter((a) => a.clientId === this.clientId())
      .sort((a, b) => b.time - a.time),
  );
}

// wealth-fdc3-react/src/components/panels/ActivityPanel.tsx
import { useState } from 'react';
import { ACTIVITY_TYPE_COLORS } from '../../data/constants';
import { CLIENTS } from '../../data/wealth-data';
import { getFdc3Agent } from '../../fdc3/agent';
import { useContactContext, useFdc3Agent } from '../../fdc3/hooks';
import { formatRelativeTime } from '../../utils/format';
import type { ActivityItem, Client, ContextMenuItem, WealthState } from '../../types';
import { ContextMenu } from '../ContextMenu';
import { Panel } from '../Panel';

interface Props {
  state: WealthState;
  onScheduleCall: (client: Client) => void;
}

export function ActivityPanel({ state, onScheduleCall }: Props) {
  const { channelColor } = useFdc3Agent();
  const contact = useContactContext();
  const clientId = contact?.id.FDS_ID ?? CLIENTS[0].id;
  const client = CLIENTS.find((c) => c.id === clientId) ?? CLIENTS[0];
  const [menu, setMenu] = useState<{ x: number; y: number; item: ActivityItem } | null>(null);

  const items = state.activity
    .filter((a) => a.clientId === client.id)
    .sort((a, b) => b.time - a.time);

  const scheduleFromActivity = () => {
    if (!menu) return;
    const c = CLIENTS.find((x) => x.id === menu.item.clientId);
    if (!c) return;
    getFdc3Agent().broadcast({
      type: 'fdc3.contact',
      id: { FDS_ID: c.id },
      name: c.name,
    });
    onScheduleCall(c);
  };

  const menuItems: ContextMenuItem[] = menu
    ? [{ label: 'Schedule Call', onClick: scheduleFromActivity }]
    : [];

  return (
    <>
      <Panel
        title={`ACTIVITY · ${client.name}`}
        channelColor={channelColor}
        scroll
        right={<span className="text-2xs text-halo-dim italic">Right-click to schedule call</span>}
      >
        {items.length === 0 ? (
          <div className="p-3 text-2xs text-halo-dim italic">No activity for this client.</div>
        ) : (
          <ul className="divide-y divide-halo-border/30">
            {items.map((item) => (
              <li
                key={item.id}
                className="px-2.5 py-1.5 hover:bg-white/[0.03] cursor-context-menu"
                onContextMenu={(e) => {
                  e.preventDefault();
                  setMenu({ x: e.clientX, y: e.clientY, item });
                }}
              >
                <div className="flex items-baseline gap-2">
                  <span
                    className="text-2xs font-bold tracking-wider"
                    style={{ color: ACTIVITY_TYPE_COLORS[item.type] }}
                  >
                    {item.type}
                  </span>
                  <span className="text-2xs text-halo-dim num ml-auto">{formatRelativeTime(item.time)}</span>
                </div>
                <div className="text-xs text-halo-text mt-0.5 leading-snug">{item.headline}</div>
                {item.detail && (
                  <div className="text-2xs text-halo-muted leading-snug mt-0.5">{item.detail}</div>
                )}
              </li>
            ))}
          </ul>
        )}
      </Panel>
      {menu && <ContextMenu x={menu.x} y={menu.y} items={menuItems} onClose={() => setMenu(null)} />}
    </>
  );
}
